import { CityCoverage, Device, Plan, Testimonial, TranslationDictionary } from "./types";

export const TRANSLATIONS: Record<string, TranslationDictionary> = {
  en: {
    brandSub: "Futuristic 5G Powered by T-Mobile",
    navPlans: "Plans",
    navCoverage: "5G Map",
    navDevices: "Store",
    navSupport: "AI Support",
    navTestimonials: "Reviews",
    getEsimBtn: "Get eSim",
    heroBadge1: "Futuristic 5G Powered by T-Mobile",
    heroBadge2: "Nationwide Zero Dead Zones",
    heroTitle1: "UNLIMITED FREEDOM.",
    heroTitle2: "FUTURE-PROOF 5G.",
    heroSub: "Experience America's ultra-low latency quantum-grade 5G network. No contracts, no hidden fees, instant QR eSIM activation.",
    shopPlansBtn: "Shop Plans Now",
    exploreMapBtn: "Live Coverage Map",
    trust1: "Nationwide 5G",
    trust2: "No Hidden Fees",
    trust3: "eSIM Instant QR",
    trust4: "Cancel Anytime",
    plansTitle: "Transparent 5G Plans",
    plansSub: "Switch in 60 seconds. Keep your number or get a fresh futuristic line.",
    mostPopular: "Most Popular",
    starterName: "Starter 5G",
    unlimitedName: "Unlimited Pro",
    familyName: "Family Hub (4 Lines)",
    perMonth: "/mo",
    selectPlanBtn: "Select Plan",
    planFeat1: "High-Speed T-Mobile 5G Network",
    planFeat2: "Unlimited Talk, Text & HD Voice",
    planFeat3: "Free Instant eSIM Activation",
    planFeat4: "Mobile Hotspot & Wi-Fi Calling",
    storeTitle: "VIVA Flagship Store",
    storeSub: "Unlocked newest iPhone & Samsung flagships + Instant eSIM kits ready for quantum 5G.",
    filterAll: "All Devices",
    filterEsim: "eSIM Kits",
    filterApple: "Apple iPhones",
    filterSamsung: "Samsung Galaxy",
    buyNowBtn: "Order Instant QR",
    orFinance: "or finance from",
    coverageTitle: "Futuristic 5G Network Coverage",
    coverageSub: "Real-time node telemetry covering all 50 US States with live signal latency visualization.",
    signalStrength: "Signal Quality",
    latency: "Avg Latency",
    uptime: "Node Uptime",
    avgSpeed: "Network Speed",
    searchCity: "Filter city or state...",
    whyTitle: "Why VIVA Mobile?",
    why1Title: "Nationwide 5G Coverage",
    why1Desc: "Powered by T-Mobile's ultra-capacity spectrum covering 330M+ Americans.",
    why2Title: "eSIM Instant Delivery",
    why2Desc: "No waiting for physical mail. Scan your personalized secure QR code & connect in seconds.",
    why3Title: "Quantum Security",
    why3Desc: "Built-in SIM swap protection and military-grade encryption on voice & data.",
    why4Title: "24/7 VIVA AI Assistant",
    why4Desc: "Zero hold times. Our futuristic Gemini-powered chatbot resolves any network query instantly.",
    testimonialsTitle: "Verified User Reviews",
    testimonialsSub: "Loved by remote workers, gamers, and tech enthusiasts across America.",
    verifiedUser: "Verified 5G Subscriber",
    chatTitle: "VIVA AI Support Bot",
    chatSub: "Online • Quantum Neural Node Active",
    chatPlaceholder: "Ask about eSIM, 5G speeds, or phone compatibility...",
    sendBtn: "Transmit",
    preset1: "How does free eSIM activation work?",
    preset2: "Check 5G signal in my state",
    preset3: "Can I bring my unlocked iPhone/Samsung?",
    footerRights: "© 2026 www.MyVivaMobile.Com — All Rights Reserved. T-Mobile is a registered trademark of Deutsche Telekom AG."
  },
  ru: {
    brandSub: "Футуристический 5G на сети T-Mobile",
    navPlans: "Тарифы",
    navCoverage: "Карта 5G",
    navDevices: "Магазин",
    navSupport: "ИИ Поддержка",
    navTestimonials: "Отзывы",
    getEsimBtn: "Получить eSim",
    heroBadge1: "Сверхбыстрый 5G от T-Mobile",
    heroBadge2: "Покрытие без мертвых зон",
    heroTitle1: "БЕЗГРАНИЧНАЯ СВОБОДА.",
    heroTitle2: "ФУТУРИСТИЧНЫЙ 5G.",
    heroSub: "Испытайте американскую сеть 5G с минимальным пингом. Без контрактов, без скрытых платежей, мгновенная активация по QR.",
    shopPlansBtn: "Выбрать тариф",
    exploreMapBtn: "Карта покрытия",
    trust1: "Покрытие США",
    trust2: "Честная цена",
    trust3: "Мгновенная eSIM",
    trust4: "Отмена в любой миг",
    plansTitle: "Прозрачные тарифы 5G",
    plansSub: "Переход за 60 секунд. Сохраните свой номер или получите новый.",
    mostPopular: "Хит продаж",
    starterName: "Стартовый 5G",
    unlimitedName: "Безлимит Pro",
    familyName: "Семейный (4 линии)",
    perMonth: "/мес",
    selectPlanBtn: "Подключить",
    planFeat1: "Высокоскоростная сеть T-Mobile 5G",
    planFeat2: "Безлимитные звонки, SMS и HD Voice",
    planFeat3: "Бесплатная мгновенная eSIM",
    planFeat4: "Режим модема и Wi-Fi Calling",
    storeTitle: "Флагманский магазин VIVA",
    storeSub: "Новейшие разблокированные iPhone и Samsung + комплекты eSIM для мгновенного старта.",
    filterAll: "Все товары",
    filterEsim: "eSIM наборы",
    filterApple: "Apple iPhone",
    filterSamsung: "Samsung Galaxy",
    buyNowBtn: "Заказать QR",
    orFinance: "или в рассрочку от",
    coverageTitle: "Карта покрытия квантового 5G",
    coverageSub: "Телеметрия вышки в реальном времени по всем 50 штатам США с отображением пинга.",
    signalStrength: "Качество сигнала",
    latency: "Средний пинг",
    uptime: "Аптайм сети",
    avgSpeed: "Скорость",
    searchCity: "Поиск города или штата...",
    whyTitle: "Почему VIVA Mobile?",
    why1Title: "Покрытие по всей стране",
    why1Desc: "Использует ультра-частоты T-Mobile, охватывающие более 330 млн жителей США.",
    why2Title: "Мгновенная eSIM",
    why2Desc: "Не нужно ждать почту. Отсканируйте защищенный QR-код и вы в сети через 30 секунд.",
    why3Title: "Квантовая защита",
    why3Desc: "Защита от подмены SIM-карты и шифрование данных военного уровня.",
    why4Title: "ИИ Ассистент 24/7",
    why4Desc: "Никаких ожиданий на линии. Наш умный ИИ мгновенно решит любой вопрос по сети.",
    testimonialsTitle: "Отзывы абонентов",
    testimonialsSub: "Выбор фрилансеров, геймеров и путешественников по всей Америке.",
    verifiedUser: "Подтвержденный абонент 5G",
    chatTitle: "ИИ Чат VIVA",
    chatSub: "В сети • Нейро-узел активирован",
    chatPlaceholder: "Спросите про eSIM, покрытие штатов или смартфоны...",
    sendBtn: "Отправить",
    preset1: "Как работает бесплатная eSIM?",
    preset2: "Проверить 5G в моем штате",
    preset3: "Поддерживает ли мой iPhone/Samsung eSIM?",
    footerRights: "© 2026 www.MyVivaMobile.Com — Все права защищены. T-Mobile является торговой маркой Deutsche Telekom AG."
  },
  es: {
    brandSub: "5G Futurista Impulsado por T-Mobile",
    navPlans: "Planes",
    navCoverage: "Mapa 5G",
    navDevices: "Tienda",
    navSupport: "Soporte IA",
    navTestimonials: "Opiniones",
    getEsimBtn: "Obtener eSim",
    heroBadge1: "Red 5G Avanzada de T-Mobile",
    heroBadge2: "Cobertura Nacional Total",
    heroTitle1: "LIBERTAD ILIMITADA.",
    heroTitle2: "5G DEL FUTURO.",
    heroSub: "Experimenta la red 5G de ultrabaja latencia en EE. UU. Sin contratos, sin cargos ocultos, activación instantánea con código QR.",
    shopPlansBtn: "Ver Planes Ahora",
    exploreMapBtn: "Mapa en Vivo",
    trust1: "5G en Todo EE. UU.",
    trust2: "Sin Cargos Ocultos",
    trust3: "eSIM al Instante",
    trust4: "Cancela Cuando Quieras",
    plansTitle: "Planes 5G Transparentes",
    plansSub: "Cámbiate en 60 segundos. Conserva tu número actual o obtén una nueva línea.",
    mostPopular: "Más Popular",
    starterName: "Starter 5G",
    unlimitedName: "Unlimited Pro",
    familyName: "Plan Familiar (4 Líneas)",
    perMonth: "/mes",
    selectPlanBtn: "Elegir Plan",
    planFeat1: "Red 5G de Alta Velocidad T-Mobile",
    planFeat2: "Llamadas y Textos Ilimitados + HD Voice",
    planFeat3: "Activación eSIM Instantánea y Gratis",
    planFeat4: "Hotspot Móvil y Llamadas Wi-Fi",
    storeTitle: "Tienda Oficial VIVA",
    storeSub: "Los últimos modelos desbloqueados de iPhone y Samsung + Kits eSIM listos para 5G.",
    filterAll: "Todos",
    filterEsim: "Kits eSIM",
    filterApple: "Apple iPhone",
    filterSamsung: "Samsung Galaxy",
    buyNowBtn: "Pedir QR Ahora",
    orFinance: "o financiado desde",
    coverageTitle: "Cobertura de Red 5G Futurista",
    coverageSub: "Monitoreo en tiempo real en los 50 estados de EE. UU. con visualización de señal.",
    signalStrength: "Calidad de Señal",
    latency: "Latencia Prom.",
    uptime: "Disponibilidad",
    avgSpeed: "Velocidad 5G",
    searchCity: "Buscar ciudad o estado...",
    whyTitle: "¿Por qué VIVA Mobile?",
    why1Title: "Cobertura en Todo el País",
    why1Desc: "Respaldado por la red de alta capacidad de T-Mobile para más de 330 millones de personas.",
    why2Title: "Entrega eSIM Instantánea",
    why2Desc: "Sin esperar envíos físicos. Escanea tu código QR seguro y conéctate al instante.",
    why3Title: "Seguridad Cuántica",
    why3Desc: "Protección contra fraude de SIM y encriptación avanzada de llamadas y datos.",
    why4Title: "Asistente IA VIVA 24/7",
    why4Desc: "Cero tiempo de espera en el teléfono. Nuestro chatbot resuelve tus dudas al segundo.",
    testimonialsTitle: "Testimonios Verificados",
    testimonialsSub: "Preferido por nómadas digitales, gamers y profesionales en Estados Unidos.",
    verifiedUser: "Suscriptor 5G Verificado",
    chatTitle: "Bot de Soporte VIVA IA",
    chatSub: "En línea • Nodo Cuántico Activo",
    chatPlaceholder: "Pregunta sobre activación eSIM, velocidad 5G o compatibilidad...",
    sendBtn: "Enviar",
    preset1: "¿Cómo funciona la activación eSIM gratis?",
    preset2: "Verificar cobertura 5G en mi estado",
    preset3: "¿Puedo usar mi teléfono desbloqueado?",
    footerRights: "© 2026 www.MyVivaMobile.Com — Todos los derechos reservados. T-Mobile es marca registrada de Deutsche Telekom AG."
  },
  lt: {
    brandSub: "Futuristinis 5G T-Mobile tinkle",
    navPlans: "Planai",
    navCoverage: "5G Žemėlapis",
    navDevices: "Parduotuvė",
    navSupport: "DI Pagalba",
    navTestimonials: "Atsiliepimai",
    getEsimBtn: "Gauti eSim",
    heroBadge1: "Pažangiausias T-Mobile 5G",
    heroBadge2: "Ryšys Visose JAV Valstijose",
    heroTitle1: "NERIBOTA LAISVĖ.",
    heroTitle2: "ATEITIES 5G RYŠYS.",
    heroSub: "Patirkite itin mažos delsos JAV 5G tinklą. Jokių sutarčių, jokių paslėptų mokesčių, akimirksniu veikianti QR eSIM aktyvacija.",
    shopPlansBtn: "Rinktis Planą",
    exploreMapBtn: "Ryšio Žemėlapis",
    trust1: "5G visose JAV",
    trust2: "Jokių slaptų mokesčių",
    trust3: "Greita QR eSIM",
    trust4: "Atšaukite bet kada",
    plansTitle: "Skaidrūs 5G Planai",
    plansSub: "Pasiimkite per 60 sekundžių. Pasilikite savo numerį arba gaukite naują futuristinę liniją.",
    mostPopular: "Populiariausias",
    starterName: "Starter 5G",
    unlimitedName: "Unlimited Pro",
    familyName: "Šeimos Planas (4 linijos)",
    perMonth: "/mėn",
    selectPlanBtn: "Pasirinkti",
    planFeat1: "Spartusis T-Mobile 5G tinklas",
    planFeat2: "Neriboti skambučiai, SMS ir HD Voice",
    planFeat3: "Nemokama momentinė eSIM aktyvacija",
    planFeat4: "Mobiliosios prieigos taškas (Hotspot)",
    storeTitle: "VIVA Flagmanų Parduotuvė",
    storeSub: "Naujausi gamykliškai atrišti iPhone ir Samsung modeliai + eSIM rinkiniai jūsų kelionėms.",
    filterAll: "Visi įrenginiai",
    filterEsim: "eSIM rinkiniai",
    filterApple: "Apple iPhone",
    filterSamsung: "Samsung Galaxy",
    buyNowBtn: "Užsisakyti QR",
    orFinance: "arba lizingu nuo",
    coverageTitle: "Futuristinis 5G Tinklo Padengimas",
    coverageSub: "Realiojo laiko telemetrija visose 50 JAV valstijų su gyvais delsos rodikliais.",
    signalStrength: "Signalo kokybė",
    latency: "Vid. delsa",
    uptime: "Veikimo laikas",
    avgSpeed: "Ryšio greitis",
    searchCity: "Ieškoti miesto ar valstijos...",
    whyTitle: "Kodėl verta rinktis VIVA?",
    why1Title: "Ryšys visose valstijose",
    why1Desc: "Naudojamas T-Mobile ultra-dažnių spektras, dengiantis virš 330 mln. JAV gyventojų.",
    why2Title: "Momentinis eSIM pristatymas",
    why2Desc: "Nereikia laukti plastikinės kortelės. Nuskaitykite saugų QR kodą ir naršykite per sekunde.",
    why3Title: "Kvantinis saugumas",
    why3Desc: "Apsauga nuo SIM vagysčių ir karinio lygio šifravimas skambučiams bei internetui.",
    why4Title: "24/7 DI Asistentas",
    why4Desc: "Jokio laukimo eilėje. Mūsų dirbtinio intelekto robotas atsakys į bet kurį klausimą akimirksniu.",
    testimonialsTitle: "Klientų Atsiliepimai",
    testimonialsSub: "Pamėgtas IT specialistų, keliautojų ir žaidėjų visoje Amerikoje.",
    verifiedUser: "Patvirtintas 5G abonentai",
    chatTitle: "VIVA DI Pokalbių Botas",
    chatSub: "Prisijungęs • Kvantinis mazgas aktyvus",
    chatPlaceholder: "Klauskite apie eSIM aktyvaciją, 5G greitį ar telefonus...",
    sendBtn: "Siųsti",
    preset1: "Kaip veikia nemokama eSIM aktyvacija?",
    preset2: "Patikrinti 5G ryšį mano valstijoje",
    preset3: "Ar mano iPhone/Samsung palaiko eSIM?",
    footerRights: "© 2026 www.MyVivaMobile.Com — Visos teisės saugomos. T-Mobile yra registruotasis Deutsche Telekom AG prekės ženklas."
  }
};

export const PLANS: Plan[] = [
  {
    id: "starter",
    name: "Starter 5G",
    price: 15,
    features: [
      "5GB Premium High-Speed 5G Data",
      "Unlimited Talk & Text Nationwide",
      "Free Instant eSIM QR Code Delivery",
      "T-Mobile Ultra-Capacity Network Access",
      "Wi-Fi Calling & VoLTE Enabled"
    ]
  },
  {
    id: "unlimited",
    name: "Unlimited Pro",
    price: 30,
    isPopular: true,
    features: [
      "Unlimited Ultra-Fast 5G Data",
      "15GB Dedicated High-Speed Hotspot",
      "4K Ultra HD Video Streaming",
      "Free Roaming in Canada & Mexico",
      "Priority Signal Node Allocation",
      "Free eSIM & Instant SIM-swap shield"
    ]
  },
  {
    id: "family",
    name: "Family Hub (4 Lines)",
    price: 45,
    features: [
      "4 Independent Lines Unlimited 5G",
      "40GB Mobile Hotspot per line",
      "Free Annual Phone Upgrade Credits",
      "Parental Controls & Cyber Shield",
      "Quantum Voice Encryption",
      "Dedicated 24/7 VIP Concierge"
    ]
  }
];

export const DEVICES: Device[] = [
  {
    id: "esim-kit",
    name: "VIVA Quantum eSIM Kit",
    brand: "eSIM",
    category: "esim",
    price: 0,
    monthly: 0,
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80",
    specs: "Instant QR Delivery • Dual SIM Compatible • 50 US States Ready",
    badge: "Free with Plan"
  },
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max (256GB)",
    brand: "Apple",
    category: "phone",
    price: 1199,
    monthly: 33.30,
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80",
    specs: "A18 Pro Chip • Grade 5 Titanium • Camera Control Button • Unlocked eSIM",
    badge: "Newest Model"
  },
  {
    id: "samsung-s25-ultra",
    name: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    category: "phone",
    price: 1299,
    monthly: 36.10,
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
    specs: "Snapdragon 8 Gen 4 • Galaxy AI Integrated • 200MP Quad Cam • S Pen Built-in",
    badge: "Galaxy AI Flagship"
  },
  {
    id: "iphone-16-plus",
    name: "iPhone 16 Plus (128GB)",
    brand: "Apple",
    category: "phone",
    price: 899,
    monthly: 24.97,
    image: "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=600&q=80",
    specs: "Ultramarine Finish • A18 Chip • Macro Photography • All-day Battery",
    badge: "Best Battery Life"
  },
  {
    id: "samsung-z-fold-6",
    name: "Samsung Galaxy Z Fold 6",
    brand: "Samsung",
    category: "phone",
    price: 1799,
    monthly: 49.99,
    image: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=600&q=80",
    specs: "7.6\" Dynamic AMOLED 2X • Armor Aluminum Frame • Multitasking Beast",
    badge: "Futuristic Foldable"
  },
  {
    id: "samsung-z-flip-6",
    name: "Samsung Galaxy Z Flip 6",
    brand: "Samsung",
    category: "phone",
    price: 1099,
    monthly: 30.52,
    image: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80",
    specs: "3.4\" FlexWindow • 50MP Camera • Compact Pocket Marvel • Quantum 5G",
    badge: "Ultra Compact"
  },
  {
    id: "iphone-se-4",
    name: "iPhone SE 4 (5G Quantum)",
    brand: "Apple",
    category: "phone",
    price: 499,
    monthly: 13.86,
    image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80",
    specs: "OLED Display • Face ID • USB-C • Superfast T-Mobile 5G Modem",
    badge: "Best Value"
  }
];

export const COVERAGE_CITIES: CityCoverage[] = [
  { id: "nyc", city: "New York", state: "New York", stateCode: "NY", lat: 40.7128, lng: -74.0060, latencyMs: 11, uptime: "99.999%", speedGbps: 1.85, signalQuality: "Ultra 5G+" },
  { id: "chi", city: "Chicago", state: "Illinois", stateCode: "IL", lat: 41.8781, lng: -87.6298, latencyMs: 12, uptime: "99.999%", speedGbps: 1.72, signalQuality: "Ultra 5G+" },
  { id: "lax", city: "Los Angeles", state: "California", stateCode: "CA", lat: 34.0522, lng: -118.2437, latencyMs: 14, uptime: "99.998%", speedGbps: 1.94, signalQuality: "Ultra 5G+" },
  { id: "mia", city: "Miami", state: "Florida", stateCode: "FL", lat: 25.7617, lng: -80.1918, latencyMs: 15, uptime: "99.999%", speedGbps: 1.68, signalQuality: "Ultra 5G+" },
  { id: "dal", city: "Dallas", state: "Texas", stateCode: "TX", lat: 32.7767, lng: -96.7970, latencyMs: 13, uptime: "99.999%", speedGbps: 1.81, signalQuality: "Ultra 5G+" },
  { id: "sea", city: "Seattle", state: "Washington", stateCode: "WA", lat: 47.6062, lng: -122.3321, latencyMs: 16, uptime: "99.997%", speedGbps: 1.65, signalQuality: "Ultra 5G+" },
  { id: "den", city: "Denver", state: "Colorado", stateCode: "CO", lat: 39.7392, lng: -104.9903, latencyMs: 14, uptime: "99.998%", speedGbps: 1.55, signalQuality: "5G Extended" },
  { id: "atl", city: "Atlanta", state: "Georgia", stateCode: "GA", lat: 33.7490, lng: -84.3880, latencyMs: 12, uptime: "99.999%", speedGbps: 1.78, signalQuality: "Ultra 5G+" },
  { id: "bos", city: "Boston", state: "Massachusetts", stateCode: "MA", lat: 42.3601, lng: -71.0589, latencyMs: 10, uptime: "99.999%", speedGbps: 1.88, signalQuality: "Peak Fiber Wireless" },
  { id: "sfo", city: "San Francisco", state: "California", stateCode: "CA", lat: 37.7749, lng: -122.4194, latencyMs: 13, uptime: "99.999%", speedGbps: 2.10, signalQuality: "Peak Fiber Wireless" },
  { id: "phx", city: "Phoenix", state: "Arizona", stateCode: "AZ", lat: 33.4484, lng: -112.0740, latencyMs: 15, uptime: "99.998%", speedGbps: 1.62, signalQuality: "Ultra 5G+" },
  { id: "phl", city: "Philadelphia", state: "Pennsylvania", stateCode: "PA", lat: 39.9526, lng: -75.1652, latencyMs: 11, uptime: "99.999%", speedGbps: 1.80, signalQuality: "Ultra 5G+" },
  { id: "det", city: "Detroit", state: "Michigan", stateCode: "MI", lat: 42.3314, lng: -83.0458, latencyMs: 13, uptime: "99.998%", speedGbps: 1.59, signalQuality: "5G Extended" },
  { id: "msp", city: "Minneapolis", state: "Minnesota", stateCode: "MN", lat: 44.9778, lng: -93.2650, latencyMs: 14, uptime: "99.998%", speedGbps: 1.64, signalQuality: "Ultra 5G+" },
  { id: "las", city: "Las Vegas", state: "Nevada", stateCode: "NV", lat: 36.1699, lng: -115.1398, latencyMs: 15, uptime: "99.999%", speedGbps: 1.95, signalQuality: "Ultra 5G+" },
  { id: "hon", city: "Honolulu", state: "Hawaii", stateCode: "HI", lat: 21.3069, lng: -157.8583, latencyMs: 28, uptime: "99.995%", speedGbps: 1.20, signalQuality: "5G Extended" },
  { id: "anc", city: "Anchorage", state: "Alaska", stateCode: "AK", lat: 61.2181, lng: -149.9003, latencyMs: 32, uptime: "99.994%", speedGbps: 1.05, signalQuality: "5G Extended" }
];

export const ALL_US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
  "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
  "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
  "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
  "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Alexey V. Smirnov",
    location: "Seattle, WA",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    quote: "Я работаю программистом удаленно. Перешел на VIVA Mobile ради пинга в 12мс на сети T-Mobile. Настройка eSIM заняла ровно 40 секунд по QR коду из почты!",
    rating: 5,
    plan: "Unlimited Pro ($30/mo)"
  },
  {
    id: "2",
    name: "Carlos M. Rodriguez",
    location: "Miami, FL",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    quote: "La velocidad de 5G es impresionante. Uso el hotspot de 15GB para trabajar en la playa sin cortes. ¡Además el roaming en México es completamente gratis!",
    rating: 5,
    plan: "Unlimited Pro ($30/mo)"
  },
  {
    id: "3",
    name: "Mantas Petrauskas",
    location: "Chicago, IL",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    quote: "Puikus ryšys Čikagoje ir keliaujant po visus JAV valstijas! Pasiėmėm šeimos planą 4 linijoms — sutaupome daugybę pinigų ir internetas tiesiog skraido.",
    rating: 5,
    plan: "Family Hub (4 Lines)"
  },
  {
    id: "4",
    name: "Sarah Jenkins",
    location: "Los Angeles, CA",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    quote: "Switching to VIVA was the best decision for my business travel. The T-Mobile 5G quantum node connectivity is unparalleled with zero dead zones!",
    rating: 5,
    plan: "Unlimited Pro ($30/mo)"
  }
];
